version: 2

jobs:
  build:
    working_directory: ~/voter-engagement

    docker:
      - image: maketested/python-node:latest
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgres://circleci:@127.0.0.1:5432/voterengagement_test
          RANDOM_SEED: 0
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          - POSTGRES_USER=circleci
          - POSTGRES_DB=voterengagement_test

    steps:
      - checkout

      - run:
          name: Checking system dependencies
          command: make doctor

      - type: cache-restore
        key: pipenv-{{ checksum "Pipfile.lock" }}
      - type: cache-restore
        key: yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Installing project dependencies
          command: make install

      - type: cache-save
        key: pipenv-{{ checksum "Pipfile.lock" }}
        paths:
          - .venv
          - tmp
      - type: cache-save
        key: yarn-{{ checksum "yarn.lock" }}
        paths:
          - node_modules
          - tmp

      - run:
          name: Checking backend code
          command: make check-backend

      - run:
          name: Running backend tests
          command: make test-backend

      - run:
          name: Running frontend tests
          command: make test-frontend
